version: "3.8"
services:
  # frontend doesnt work with vite

  #so if you are in development mode:
  #comment out this component and use vite instead----------------------------------
  #open terminal go to ./front-end and run "npm run dev"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "3000:3000"
  #comment out this component and use vite instead----------------------------------

  auth:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  game_master:
    build:
      context: ./game_master
      dockerfile: Dockerfile.dev
    volumes:
      - ./game_master:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    depends_on:
      - postgres
      - mongodb
    ports:
      - "5001:5001"

  game_play:
    build:
      context: ./game_play
      dockerfile: Dockerfile.dev
    volumes:
      - ./game_play:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    depends_on:
      - postgres
      - mongodb
    ports:
      - "5002:5002"

  #dbs
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./postgres_init/database.sql:/docker-entrypoint-initdb.d/create-tables.sql
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
volumes:
  mongodb:
  mongodb_config:
